name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .  # ship everything in the repo root

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
